# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               SolarSpish Blog
tagline:             ''
description:         'I am the Lead Programmer at <a href="http://ironcladgames.com" target="_blank">Ironclad Games</a>. You can find me on Twitter <a href="https://twitter.com/spish" target="_blank">@spish</a>. Or streaming on <a href="http://www.twitch.tv/solarspish" target="_blank">Twitch</a>.'
url:                 http://jseward.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Jamie Seward
  url:               https://twitter.com/spish
  email:             

# Custom vars
version:             1.0.0
